### ISSUE TITLE
Add Feature Status Online and Offline PPPoE Client

### ISSUE THREAD

**Issue by choirulsite** [hotspotbilling/phpnuxbill#100]
Add Feature Total Status Online and Offline PPPoE Client.
details of every online n ofline from client

**Comment by ibnux** [comment]
There's plugin Mikrotik Info for that

**Comment by ibnux** [comment]
Silahkan rekues ke pembuat pluginnya

Karena ngga ada rencana untuk ditambahkan ke core system


Jika tetap ingin ada fiturnya, biayanya Rp. 3.000.000
