### ISSUE TITLE
FreeRadius Intregation

### ISSUE THREAD

**Issue by ibnux** [hotspotbilling/phpnuxbill#11]
FreeRADIUS authenticates users and tracks accounting data for millions of DSL connections and phones every day. Enterprise Networks. Global AAA servers

[https://freeradius.org/](https://freeradius.org/)

**Comment by fuchmi** [comment]
pantau radius untuk phpnuxbill..
dan siap donasi....

**Comment by fuchmi** [comment]
akhirnya aktif juga freeradius thanks kang
