### ISSUE TITLE
Payment gateway Failed to create transaction

### ISSUE THREAD

**Issue by lemowa** [hotspotbilling/phpnuxbill#113]
Payment gateway duitku Failed to create transaction
Untuk kode merchant dan api key sudah sesuai namun selalu gagal membuat transaksi

atau ada rekomendasi lainnya untuk payment gateway yang dipergunakan ?

**Comment by dutatopup** [comment]
mode sandbox apa production yg dipake? klo mode sandbox ubah dulu LIVE ke DEV di file config.php nya, kalo mode production ubah lagi dari DEV ke LIVE
