### ISSUE TITLE
Penambahan fitur Notifikasi Whatsapp

### ISSUE THREAD

**Issue by choirulsite** [hotspotbilling/phpnuxbill#14]
Penambahan Fitur Notifikasi Whatsapp/pemberitahuan ke pelanggan ketika sudah jatuh tempo pembayaran (setelah Cron berjalan dan pelanggan status off)

**Comment by edwinb4li** [comment]
> 

cron aktif pake linux pak? klo jatuh tempo auto pppoe delete kah?

**Comment by choirulsite** [comment]
Cron jalan pake windows.. dg metode schedule

**Comment by choirulsite** [comment]
Jatuh tempo auto disable

**Comment by edwinb4li** [comment]
> Jatuh tempo auto disable

klo auto remove ppp userActive kok ga bisa ya? apa karena $onlineRequest bukanya $printRequest?
 public static function removePpoeActive($client, $username)
    {
        $onlineRequest = new RouterOS\Request('/ppp/active/print');
        $onlineRequest->setArgument('.proplist', '.id');
        $onlineRequest->setQuery(RouterOS\Query::where('name', $username));
        $id = $client->sendSync($onlineRequest)->getProperty('.id');

        $removeRequest = new RouterOS\Request('/ppp/active/remove');
        $removeRequest->setArgument('numbers', $id);
        $client->sendSync($removeRequest);
    }

**Comment by edwinb4li** [comment]
> Jatuh tempo auto disable

Mikrotik::removePpoeActive($client,$c['username']);

koreksi klo salah, jadi ketika replace paket mw bikin auto remove user ppp active

**Comment by choirulsite** [comment]
intinya ketika waktu recharge account itu, ppp yang aktif bisa diremove? tambah script di prepaid.php, di atas pppoe

**Comment by ibnux** [comment]
Pada cron saya buat disable dulu, baru remove user yang sudah tidak aktif

https://github.com/hotspotbilling/phpnuxbill/blob/50e55744ec527bccc0a0604b8e07d61d5651589f/system/cron.php#L95-L96

recharge dan pembelian paket akan hapus existing user dan ditambahkan lagi, jadi kalo user belum habis suatu paket, dan beli paket baru, yang lama akan dihapus lagi, dan ditambahkan ke paket baru

**Comment by edwinb4li** [comment]
> Penambahan Fitur Notifikasi Whatsapp/pemberitahuan ke pelanggan ketika sudah jatuh tempo pembayaran (setelah Cron berjalan dan pelanggan status off)

klo yg ini sudah masuk gan di cron?

**Comment by edwinb4li** [comment]
> Pada cron saya buat disable dulu, baru remove user yang sudah tidak aktif
> 
> https://github.com/hotspotbilling/phpnuxbill/blob/50e55744ec527bccc0a0604b8e07d61d5651589f/system/cron.php#L95-L96
> 
> recharge dan pembelian paket akan hapus existing user dan ditambahkan lagi, jadi kalo user belum habis suatu paket, dan beli paket baru, yang lama akan dihapus lagi, dan ditambahkan ke paket baru

mantabbb

**Comment by ibnux** [comment]
>  
> 
> > Penambahan Fitur Notifikasi Whatsapp/pemberitahuan ke pelanggan ketika sudah jatuh tempo pembayaran (setelah Cron berjalan dan pelanggan status off)
> 
> klo yg ini sudah masuk gan di cron?

Belum, ini baru rekues, akan dikerjakan di waktu senggang

Rekues dari donatur biasanya saya cepat buat

Seperti plugin ini
https://github.com/hotspotbilling/phpnuxbill-plugin-mikrotik-import

**Comment by edwinb4li** [comment]
> Cron jalan pake windows.. dg metode schedule

pernah hosting phpmixbill id hostinger? kok ga bisa konek ke router ya? posisi router sudah ip publik... apakah harus di buat forwarding di router atau yg salah di hostingnya?

**Comment by ibnux** [comment]
> > Cron jalan pake windows.. dg metode schedule
> 
> 
> 
> pernah hosting phpmixbill id hostinger? kok ga bisa konek ke router ya? posisi router sudah ip publik... apakah harus di buat forwarding di router atau yg salah di hostingnya?

Silahkan bikin issue baru atau diskusi baru

Jangan merusak diskusi orang diluar topik

**Comment by choirulsite** [comment]
> Pada cron saya buat disable dulu, baru remove user yang sudah tidak aktif
> 
> https://github.com/hotspotbilling/phpnuxbill/blob/50e55744ec527bccc0a0604b8e07d61d5651589f/system/cron.php#L95-L96
> 
> recharge dan pembelian paket akan hapus existing user dan ditambahkan lagi, jadi kalo user belum habis suatu paket, dan beli paket baru, yang lama akan dihapus lagi, dan ditambahkan ke paket baru

Punya saya saya edit untuk dibelokkan ke ip expired.. jadi harus menambah remove pppoe aktif di prepaid...

**Comment by edwinb4li** [comment]
> > Pada cron saya buat disable dulu, baru remove user yang sudah tidak aktif
> > https://github.com/hotspotbilling/phpnuxbill/blob/50e55744ec527bccc0a0604b8e07d61d5651589f/system/cron.php#L95-L96
> > 
> > recharge dan pembelian paket akan hapus existing user dan ditambahkan lagi, jadi kalo user belum habis suatu paket, dan beli paket baru, yang lama akan dihapus lagi, dan ditambahkan ke paket baru
> 
> Punya saya saya edit untuk dibelokkan ke ip expired.. jadi harus menambah remove pppoe aktif di prepaid...

gan, klo database transakstion methodnya di tambah sesuai dengan teknisi bagaimana ya?

**Comment by fuchmi** [comment]
> 

siap donasi

**Comment by ibnux** [comment]
On Progress

![Image](https://user-images.githubusercontent.com/811955/223039630-493e4ee0-df4b-4100-8222-b6903461fcf2.png)

**Comment by fuchmi** [comment]
![Screenshot_2023-03-06-14-34-12-28_f339d16c976c0b263d991820e972fb72](https://user-images.githubusercontent.com/112465990/223046558-623378d0-a2a6-42c8-b363-f5c266fb8774.jpg)
Semoga tambah semangat... Dengan dukungan kecil ini...

**Comment by ibnux** [comment]
Sudah selesai, silahkan di test 

Menu nya ada di Pengaturan umum

Unduh [disini](https://github.com/hotspotbilling/phpnuxbill/archive/refs/heads/Development.zip

![Image](https://user-images.githubusercontent.com/811955/223051298-d2298e43-615a-4edd-88b3-c0299167c124.png)

)

**Comment by fuchmi** [comment]
![Screenshot 2023-03-06 154647](https://user-images.githubusercontent.com/112465990/223061139-2a35b8bd-219d-4d05-bc48-3f6675c38fe7.jpg)
apakah sudah benar config Whatsapp Server URL nya

**Comment by ibnux** [comment]
@fuchmi iya, harusnya itu benar

**Comment by edwinb4li** [comment]
ini klo pake whatsapp notifikasi harus di replace apa aja? app setting dan cron kah?
