### ISSUE TITLE
Search customer di menu recahrge account

### ISSUE THREAD

**Issue by choirulsite** [hotspotbilling/phpnuxbill#19]
Search customer pada menu recahrge account di versi android/mobile tidak muncul... 
Membuat kesulitan untuk memilih customer yang akan di recharge account.. karna harus men scroll ke bawah....

**Comment by edwinb4li** [comment]
search costumer pake username apa full name? kan bisa buka costumer list untuk recharge,,,,

**Comment by choirulsite** [comment]
Buat apa ada menu recharge account jika harus masuk customer list  untuk mencari account yg harus diaktifkan..
Lbih efektif ada menu search di menu recharge account

**Comment by ibnux** [comment]
Fixed di Repo Private
