### ISSUE TITLE
Time and duration calculation bug.

### ISSUE THREAD

**Issue by rems25000** [hotspotbilling/phpnuxbill#190]
Good morning,
I detected different time display and duration calculation bugs.
for my case I only use radius plans without mikrotik and it works very well.

-The person buys a 24Hrs pack at "01 May 2024 22:05" the end date is the correct one "02 May 2024 22:05"  -> OK
-The person buys a 24Hrs plan at "02 May 2024 00:26" the end date displayed is "03 May 2024 22:05" -> NOK
It should be "03 May 2024 00:26"?

screen copy on admin side /index.php?_route=customers/view/1
![image](https://github.com/hotspotbilling/phpnuxbill/assets/97801362/ed566bb5-5653-4802-b6da-ae6366fb30e4)

screen copy on user side:

On the following 3 screenshots, there is no consistency in the dates and times. /index.php?_route=order/history
![image](https://github.com/hotspotbilling/phpnuxbill/assets/97801362/09a0837e-60b0-4fb5-bac6-bab11837a8a1)
![image](https://github.com/hotspotbilling/phpnuxbill/assets/97801362/ba2561e5-cd6e-42b8-90d3-1ecdcb513c35)
/index.php?_route=home
![image](https://github.com/hotspotbilling/phpnuxbill/assets/97801362/00123e57-05af-48a8-a3f0-466debcd7dfe)

Can you see if it's wrong?

![image](https://github.com/hotspotbilling/phpnuxbill/assets/97801362/350a0a3b-3c6f-4e7c-b984-acf235479b9a)
system and database time is ok.

Sincerely

**Comment by ibnux** [comment]
@rems25000 its not a bug, is from past code when still phpmixbill, i fix it now to follow current time when it expired
