### ISSUE TITLE
whatsapp notice error

### ISSUE THREAD

**Issue by fuchmi** [hotspotbilling/phpnuxbill#21]
Whatsapp Error
From: 628116801087
To: 082273309190
Message:
*RF Intermedia*
Dusun Mesjid lama
Keude Aceh
0822xxxxxxx

Error:
{
    "status": false,
    "code": 500,
    "error": "failed to get device list: failed to send usync query: info query timed out"
}

**Comment by choirulsite** [comment]
Ini notif whatsapp apa payment whatsapp.... punya saya aman

**Comment by fuchmi** [comment]
Waktu pembelian paket, WhatsApp nya errror gk mau kirim

**Comment by ibnux** [comment]
Di server WhatsApp kirim test pesan sukses ngga?
