### ISSUE TITLE
Bkash Payment Gatwey

### ISSUE THREAD

**Issue by baijed** [hotspotbilling/phpnuxbill#24]
assalamu alaikum sir
how do add Bkash Payment Gatwey (BD Payment System)
i'will provide "Bkash" all file with demo sandbox..... 
Please Help....

**Comment by ibnux** [comment]
You can chat to my telegram @ibnux

It will be good if the payment gateway can add additional member/developer

If not, I need your account to learn how bkash works.

After it done, you just change the password again
