### ISSUE TITLE
user delete bug

### ISSUE THREAD

**Issue by hellracer** [hotspotbilling/phpnuxbill#38]
When deleting a user  a dialog box appear when you click cancel the user still being deleted, i believed  bootbox is not loaded properly.
potential replacement https://bootstrap-confirmation.js.org/ 

```
 $(document).on("click", ".cdelete", function(e) {
            e.preventDefault();
                        var id = this.id;
                        bootbox.confirm("Are you sure?", function(result) {
                                if(result){
                                        window.location.href = "index.php?_route=settings/users-delete/" + id;
                                }
                        });
        });
```
anyway all delete function from various forms exhibit this behavior not only a delete function under the customer template

**Comment by ibnux** [comment]
Fixed 

forgot to add `return` it must be `onclick="return confirm(`
