### ISSUE TITLE
error 500 generating pdf

### ISSUE THREAD

**Issue by hellracer** [hotspotbilling/phpnuxbill#40]
current bundle mpdf v6 is way too old, please update :) i'm on ubuntu 22.04 with php 8.1.2

**Comment by hellracer** [comment]
installing latest mpdf via composer and adjusting vendor file to your linking will fix the issue and instantiate a new object with 
$mpdf = new \Mpdf\Mpdf(); 

I don't adjust any of your code it simply works

**Comment by ibnux** [comment]
Thank you for the bug information

now i am using composer to update mpdf and smarty

**Comment by ibnux** [comment]
fixed in private repository
