### ISSUE TITLE
database restore from UI 

### ISSUE THREAD

**Issue by hellracer** [hotspotbilling/phpnuxbill#41]
Database backup is available from UI Settings -> Backup/Restore but restore functionality is missing and that is candidate for enhancement 💯

**Comment by ibnux** [comment]
restoring database using PHPMyadmin

maybe i will add import for phpnuxbill

**Comment by ibnux** [comment]
I disable backup
Better backup via phpmyadmin


And now I add sync to mikrotik

So after restoring, you can sync data to mikrotik again
