### ISSUE TITLE
PHP ZIP extension is not available

### ISSUE THREAD

**Issue by sarifulshikder** [hotspotbilling/phpnuxbill#58]
When Trying to Install a Payment Gateway it says PHP ZIP extension not available. I was Install Docker Container in my Mikrotik router and then install phpnuxbill image in this container. everything works fine without installing payment gateway . please help me
![Screenshot 2023-08-08 162629](https://github.com/hotspotbilling/phpnuxbill/assets/90824320/f8a11078-b744-4c74-bf50-5915eae71daf)

**Comment by ibnux** [comment]
you can directly ask the creator

https://github.com/animegasan/phpnuxbill

**Comment by ibnux** [comment]
Please wait, the creator of docker version will update soon

**Comment by sarifulshikder** [comment]
ok sir  waiting

**Comment by sarifulshikder** [comment]
updated 3 months ago

**Comment by sarifulshikder** [comment]
Sir i am still waiting for zip extension

**Comment by ibnux** [comment]
i am not creator of that docker
so you will not get anything in here, create issue in their repo
