### ISSUE TITLE
Tidak ada kolom E-Mail

### ISSUE THREAD

**Issue by Overwatch-C-17** [hotspotbilling/phpnuxbill#59]
Saat login sebagai admin, dan ingin menambahkan kontak pelanggan secara manual melalui **Kontak Member >> Tambahkan Kontak**, admin tidak bisa mengisi E-Mail untuk pelanggan baru karena tidak terdapat kolom E-Mail untuk diisi

**Comment by ibnux** [comment]
Done, wait for update
