### ISSUE TITLE
Error menambahkan Router di Network --> Router Baru

### ISSUE THREAD

**Issue by ahmadhusein17** [hotspotbilling/phpnuxbill#60]
Mohon bantuannya pak, saya kendala tidak dapat menambahkan Router. Saya sudah coba menggunakan hosting rumahweb.com + hostingtermurah.com tidak bisa. Tapi saya coba di 000webhostapp normal .
Saya sudah rubah versi PHP 7.4 padahal tapi alhasil masih nihil. Saya tidak punya uang lebih untuk berlangganan di hosting mahal.
Berikut saya lampirkan hasil error nya 
![Screenshot_20230812-131117](https://github.com/hotspotbilling/phpnuxbill/assets/48185559/400e2ff1-603d-4879-a5a4-23aa868332aa)
![72013](https://github.com/hotspotbilling/phpnuxbill/assets/48185559/8f51653c-60d4-4187-90d3-c1a8cb698dea)

**Comment by AlfiFazulul** [comment]
sama kaya gue bang gabisa, sekarang gimana bg udah bisa?

**Comment by AlfiFazulul** [comment]
> Mohon bantuannya pak, saya kendala tidak dapat menambahkan Router. Saya sudah coba menggunakan hosting rumahweb.com + hostingtermurah.com tidak bisa. Tapi saya coba di 000webhostapp normal . Saya sudah rubah versi PHP 7.4 padahal tapi alhasil masih nihil. Saya tidak punya uang lebih untuk berlangganan di hosting mahal. Berikut saya lampirkan hasil error nya ![Screenshot_20230812-131117](https://user-images.githubusercontent.com/48185559/260205625-400e2ff1-603d-4879-a5a4-23aa868332aa.jpg) ![72013](https://user-images.githubusercontent.com/48185559/260206263-8f51653c-60d4-4187-90d3-c1a8cb698dea.png)

sama kaya gue bang gbsa, sekarang udah bisa?
