### ISSUE TITLE
gk bisa buka/liat custumer

### ISSUE THREAD

**Issue by fuchmi** [hotspotbilling/phpnuxbill#70]
gk bisa liat atau klik di custumer

![Screenshot 2023-09-27 205134](https://github.com/hotspotbilling/phpnuxbill/assets/112465990/74f86857-a079-44ff-849c-b234b4c0918f)
![2023-09-27 205251](https://github.com/hotspotbilling/phpnuxbill/assets/112465990/7e395b1f-ef39-497b-81de-f2600d053af2)

**Comment by ibnux** [comment]
Ganti PHP 7
