### ISSUE TITLE
error adding routeros

### ISSUE THREAD

**Issue by hidagans** [hotspotbilling/phpnuxbill#74]
#0 /home/mediailm/billing.mediailmu.cloud/system/autoload/PEAR2/Net/RouterOS/Client.php(157): PEAR2\Net\RouterOS\Communicator->__construct()
#1 /home/mediailm/billing.mediailmu.cloud/system/autoload/Mikrotik.php(21): PEAR2\Net\RouterOS\Client->__construct()
#2 /home/mediailm/billing.mediailmu.cloud/system/controllers/routers.php(98): Mikrotik::getClient()
#3 /home/mediailm/billing.mediailmu.cloud/system/boot.php(344): include('/home/mediailm/...')
#4 /home/mediailm/billing.mediailmu.cloud/index.php(22): require_once('/home/mediailm/...')
#5 {main}

**Comment by ibnux** [comment]
Ini bukan bug

Aplikasinya tidak dapat mengakses port api routernya

Silahkan tanya di komunitas

https://t.me/phpnuxbill
